### ISSUE TITLE
Deploy this example to Digital Ocean fails

### ISSUE THREAD

**Issue by zarubto4** [digitalocean/sample-functions-nodejs-helloworld#7]
Hi, copy paste to Digital Ocean return errors. 
So this tutorial is no more valid. Please make a fix .  

{
  "code": "0ac152ca8588760e083545de29a54191",
  "error": "Incomplete web function path. The path must contain /$namespace/$package/$function, $package can be 'default'."
}

**Comment by wei** [comment]
Same issue. Opened #8
